global using FluentValidation;
global using MongoDB.Bson;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using MongoDB.Bson.Serialization.Attributes;
global using ecommerce_core.Helpers;
global using ecommerce_core.Dtos.Auth;
global using FluentValidation.AspNetCore;
global using Microsoft.Extensions.DependencyInjection;
